-- ============================================================================
-- seed_data.sql
-- Deterministically generated sample data. Do not hand-edit -- regenerate with
-- scripts/generate_seed_data.py if you need to change the dataset.
-- ============================================================================

-- Customers (note: customer_id 4 and 15 share the SAME name on purpose --
-- see docs/common-pitfalls.md, Pitfall #1: joining on the wrong key).
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (1, 'Patricia Martinez', 'Toronto', 'Canada', 'patricia.martinez1@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (2, 'Michael Lee', 'Cleveland', 'USA', 'michael.lee2@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (3, 'Nancy White', 'Montreal', 'Canada', 'nancy.white3@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (4, 'Sarah Johnson', 'Detroit', 'USA', 'sarah.johnson4@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (5, 'Maria Moore', 'Louisville', 'USA', 'maria.moore5@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (6, 'Lisa Wilson', 'Detroit', 'USA', 'lisa.wilson6@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (7, 'Jennifer Thompson', 'Cincinnati', 'USA', 'jennifer.thompson7@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (8, 'Jennifer Harris', 'Detroit', 'USA', 'jennifer.harris8@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (9, 'James Davis', 'Cleveland', 'USA', 'james.davis9@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (10, 'Paul Wilson', 'Columbus', 'USA', 'paul.wilson10@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (11, 'Patricia Harris', 'Louisville', 'USA', 'patricia.harris11@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (12, 'David Lee', 'Detroit', 'USA', 'david.lee12@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (13, 'David Taylor', 'Detroit', 'USA', 'david.taylor13@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (14, 'Daniel Thomas', 'Chicago', 'USA', 'daniel.thomas14@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (15, 'Sarah Johnson', 'Toronto', 'Canada', 'sarah.johnson15@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (16, 'Patricia Perez', 'Detroit', 'USA', 'patricia.perez16@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (17, 'Susan Thomas', 'Pittsburgh', 'USA', 'susan.thomas17@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (18, 'Paul Clark', 'Chicago', 'USA', 'paul.clark18@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (19, 'Jennifer Garcia', 'Cincinnati', 'USA', 'jennifer.garcia19@example.com');
INSERT INTO customers (customer_id, customer_name, city, country, email) VALUES (20, 'Jennifer Moore', 'Louisville', 'USA', 'jennifer.moore20@example.com');

-- Employees (commission is NULL for salaried roles -- see the COALESCE exercise).
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (1, 'Maria Johnson', 'Account Executive', '2020-07-17', 0.03);
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (2, 'Lisa Miller', 'Senior Account Executive', '2023-04-06', 0.05);
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (3, 'James Harris', 'Sales Development Rep', '2020-09-28', 0.04);
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (4, 'William Lee', 'Sales Operations Analyst', '2022-02-11', NULL);
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (5, 'David Martin', 'Sales Manager', '2023-12-20', NULL);
INSERT INTO employees (employee_id, employee_name, title, hire_date, commission) VALUES (6, 'Daniel Johnson', 'Customer Success Manager', '2023-03-23', NULL);

-- Products.
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (1, 'Standing Desk Converter', 'Office Furniture', 189.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (2, 'Ergonomic Mesh Chair', 'Office Furniture', 249.50);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (3, '27in 4K Monitor', 'Electronics', 329.00);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (4, 'Mechanical Keyboard', 'Electronics', 89.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (5, 'Wireless Mouse', 'Electronics', 34.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (6, 'USB-C Docking Station', 'Electronics', 159.00);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (7, 'LED Desk Lamp', 'Office Supplies', 42.75);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (8, 'Noise-Cancelling Headset', 'Electronics', 199.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (9, 'Whiteboard 4x6', 'Office Supplies', 74.25);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (10, 'Filing Cabinet 3-Drawer', 'Office Furniture', 139.00);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (11, 'Laptop Stand', 'Office Supplies', 29.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (12, 'Surge Protector', 'Electronics', 24.50);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (13, 'Bookshelf 5-Tier', 'Office Furniture', 119.99);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (14, 'Conference Room Speakerphone', 'Electronics', 279.00);
INSERT INTO products (product_id, product_name, category, unit_price) VALUES (15, 'Paper Shredder', 'Office Supplies', 94.99);

-- Orders (customer_id 19 and 20 deliberately have NO orders -- see the
-- LEFT JOIN and 'filtering in WHERE vs ON' exercises).
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (1, 4, 5, '2023-06-22', '2023-06-23', 998.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (2, 18, 4, '2024-08-01', '2024-08-06', 1251.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (3, 11, 5, '2023-08-21', '2023-08-25', 959.92);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (4, 17, 3, '2023-08-10', '2023-08-11', 1546.46);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (5, 16, 6, '2024-12-06', '2024-12-13', 2145.92);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (6, 13, 4, '2024-01-20', '2024-01-26', 2981.98);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (7, 16, 3, '2023-06-29', '2023-07-01', 1198.40);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (8, 17, 6, '2023-06-04', NULL, 664.93);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (9, 5, 4, '2024-06-27', NULL, 1005.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (10, 7, 5, '2024-10-19', '2024-10-25', 3924.43);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (11, 3, 6, '2024-11-22', NULL, 1938.87);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (12, 15, 4, '2023-10-28', '2023-11-06', 894.87);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (13, 8, 2, '2024-06-12', '2024-06-15', 3179.65);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (14, 10, 1, '2023-12-24', NULL, 384.75);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (15, 12, 3, '2024-02-07', '2024-02-09', 3402.94);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (16, 7, 4, '2024-03-09', '2024-03-11', 34.99);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (17, 6, 2, '2024-08-29', '2024-09-07', 2166.93);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (18, 18, 4, '2024-09-04', '2024-09-14', 2035.92);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (19, 13, 2, '2024-03-04', '2024-03-10', 399.92);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (20, 18, 2, '2024-04-03', '2024-04-06', 474.95);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (21, 9, 6, '2024-05-15', '2024-05-24', 188.23);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (22, 16, 6, '2023-10-06', '2023-10-08', 1062.97);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (23, 12, 4, '2024-09-30', '2024-10-01', 857.90);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (24, 11, 6, '2023-07-17', '2023-07-22', 1991.50);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (25, 10, 1, '2024-06-09', '2024-06-18', 1552.81);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (26, 12, 4, '2024-09-07', '2024-09-17', 5108.35);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (27, 15, 1, '2023-11-22', '2023-12-01', 1512.93);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (28, 7, 5, '2024-02-23', '2024-02-28', 6200.50);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (29, 8, 1, '2023-11-16', '2023-11-19', 999.84);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (30, 17, 5, '2024-09-19', '2024-09-20', 2047.46);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (31, 9, 1, '2024-11-15', '2024-11-18', 2382.29);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (32, 5, 6, '2024-01-22', NULL, 2232.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (33, 18, 6, '2024-08-18', '2024-08-25', 449.95);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (34, 10, 3, '2024-10-23', NULL, 1951.96);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (35, 5, 3, '2024-04-01', '2024-04-10', 2873.48);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (36, 7, 5, '2024-10-27', NULL, 837.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (37, 11, 6, '2024-02-07', '2024-02-13', 4286.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (38, 11, 1, '2024-03-24', NULL, 1820.42);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (39, 2, 5, '2024-05-05', NULL, 2448.95);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (40, 9, 4, '2024-06-16', '2024-06-18', 4244.92);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (41, 10, 2, '2024-04-06', '2024-04-08', 799.96);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (42, 1, 2, '2024-06-29', '2024-07-04', 3975.85);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (43, 12, 2, '2024-01-14', '2024-01-22', 562.50);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (44, 7, 1, '2023-10-15', '2023-10-24', 2084.89);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (45, 5, 6, '2023-10-29', '2023-11-08', 1959.88);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (46, 16, 4, '2024-08-12', '2024-08-15', 4498.86);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (47, 12, 4, '2024-03-19', '2024-03-24', 4817.75);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (48, 1, 2, '2024-03-28', '2024-03-29', 379.96);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (49, 1, 5, '2023-08-25', '2023-09-03', 705.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (50, 7, 3, '2024-01-17', '2024-01-18', 98.00);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (51, 12, 6, '2024-03-06', '2024-03-16', 894.18);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (52, 17, 1, '2023-08-28', NULL, 3960.90);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (53, 10, 2, '2023-07-23', '2023-07-24', 1685.99);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (54, 12, 6, '2024-02-29', '2024-03-06', 2540.44);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (55, 15, 3, '2023-10-24', '2023-11-03', 3942.08);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (56, 5, 5, '2023-08-13', '2023-08-17', 3048.50);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (57, 9, 5, '2023-09-18', '2023-09-28', 239.98);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (58, 14, 1, '2024-01-27', '2024-02-03', 3448.36);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (59, 16, 4, '2024-03-01', '2024-03-06', 2605.86);
INSERT INTO orders (order_id, customer_id, employee_id, order_date, ship_date, total_amount) VALUES (60, 14, 2, '2024-11-20', '2024-11-21', 371.25);

-- Order details (Quantity * UnitPrice is the running LineTotal example).
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (1, 1, 2, 4, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (2, 2, 10, 9, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (3, 3, 13, 8, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (4, 4, 2, 3, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (5, 4, 6, 2, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (6, 4, 13, 4, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (7, 5, 6, 8, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (8, 5, 5, 8, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (9, 5, 9, 8, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (10, 6, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (11, 6, 8, 2, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (12, 6, 14, 1, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (13, 7, 5, 5, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (14, 7, 12, 3, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (15, 7, 1, 5, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (16, 8, 15, 7, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (17, 9, 7, 4, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (18, 9, 10, 6, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (19, 10, 15, 7, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (20, 10, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (21, 10, 12, 5, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (22, 10, 10, 6, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (23, 11, 2, 2, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (24, 11, 4, 4, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (25, 11, 13, 9, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (26, 12, 5, 5, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (27, 12, 4, 8, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (28, 13, 13, 10, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (29, 13, 7, 7, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (30, 13, 2, 1, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (31, 13, 6, 9, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (32, 14, 7, 9, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (33, 15, 2, 8, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (34, 15, 14, 3, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (35, 15, 15, 6, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (36, 16, 5, 1, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (37, 17, 14, 3, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (38, 17, 1, 7, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (39, 18, 15, 8, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (40, 18, 2, 4, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (41, 18, 10, 2, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (42, 19, 1, 1, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (43, 19, 11, 7, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (44, 20, 15, 5, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (45, 21, 11, 2, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (46, 21, 7, 3, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (47, 22, 10, 7, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (48, 22, 11, 3, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (49, 23, 11, 10, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (50, 23, 14, 2, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (51, 24, 6, 7, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (52, 24, 3, 2, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (53, 24, 12, 9, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (54, 25, 4, 10, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (55, 25, 15, 4, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (56, 25, 12, 4, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (57, 25, 5, 5, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (58, 26, 13, 8, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (59, 26, 9, 6, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (60, 26, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (61, 26, 8, 7, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (62, 27, 6, 4, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (63, 27, 15, 5, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (64, 27, 11, 2, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (65, 27, 7, 8, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (66, 28, 6, 1, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (67, 28, 7, 6, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (68, 28, 3, 10, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (69, 28, 2, 10, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (70, 29, 15, 8, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (71, 29, 11, 8, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (72, 30, 2, 5, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (73, 30, 8, 4, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (74, 31, 5, 6, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (75, 31, 12, 5, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (76, 31, 4, 8, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (77, 31, 1, 7, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (78, 32, 14, 8, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (79, 33, 4, 5, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (80, 34, 2, 4, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (81, 34, 9, 8, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (82, 34, 4, 4, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (83, 35, 15, 1, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (84, 35, 9, 6, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (85, 35, 11, 1, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (86, 35, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (87, 36, 14, 3, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (88, 37, 2, 10, 249.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (89, 37, 6, 6, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (90, 37, 14, 3, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (91, 38, 12, 9, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (92, 38, 8, 8, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (93, 39, 3, 6, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (94, 39, 15, 5, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (95, 40, 8, 8, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (96, 40, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (97, 40, 7, 8, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (98, 41, 8, 4, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (99, 42, 6, 7, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (100, 42, 10, 7, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (101, 42, 1, 9, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (102, 42, 11, 6, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (103, 43, 12, 9, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (104, 43, 7, 8, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (105, 44, 10, 5, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (106, 44, 1, 1, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (107, 44, 13, 10, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (108, 45, 4, 9, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (109, 45, 12, 8, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (110, 45, 13, 3, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (111, 45, 9, 8, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (112, 46, 6, 2, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (113, 46, 11, 9, 29.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (114, 46, 1, 5, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (115, 46, 3, 9, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (116, 47, 1, 10, 189.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (117, 47, 8, 7, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (118, 47, 13, 8, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (119, 47, 14, 2, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (120, 48, 15, 4, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (121, 49, 12, 6, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (122, 49, 14, 2, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (123, 50, 12, 4, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (124, 51, 5, 7, 34.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (125, 51, 9, 5, 74.25);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (126, 51, 10, 2, 139.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (127, 52, 14, 4, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (128, 52, 13, 10, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (129, 52, 3, 5, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (130, 53, 7, 4, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (131, 53, 13, 1, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (132, 53, 14, 5, 279.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (133, 54, 12, 1, 24.50);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (134, 54, 8, 6, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (135, 54, 3, 4, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (136, 55, 13, 9, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (137, 55, 7, 3, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (138, 55, 15, 8, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (139, 55, 3, 6, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (140, 56, 3, 7, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (141, 56, 6, 2, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (142, 56, 7, 10, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (143, 57, 13, 2, 119.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (144, 58, 6, 7, 159.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (145, 58, 8, 9, 199.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (146, 58, 7, 2, 42.75);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (147, 58, 4, 5, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (148, 59, 4, 8, 89.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (149, 59, 3, 4, 329.00);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (150, 59, 15, 6, 94.99);
INSERT INTO order_details (order_detail_id, order_id, product_id, quantity, unit_price) VALUES (151, 60, 9, 5, 74.25);

-- Support tickets: name-only legacy feed, no customer_id available.
-- Ticket 1 is deliberately for the ambiguous 'Sarah Johnson' -- see
-- exercises/03_joins.sql, Q5.
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (1, 'Sarah Johnson', 'Billing question', '2024-02-10');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (2, 'James Davis', 'Billing question', '2023-11-21');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (3, 'Paul Wilson', 'Damaged item', '2024-02-21');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (4, 'Jennifer Garcia', 'Billing question', '2024-06-19');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (5, 'Susan Thomas', 'Return request', '2024-08-25');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (6, 'Patricia Harris', 'Product question', '2024-07-07');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (7, 'Jennifer Garcia', 'Damaged item', '2024-10-14');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (8, 'Jennifer Harris', 'Damaged item', '2024-01-26');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (9, 'Jennifer Garcia', 'Shipping delay', '2024-12-16');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (10, 'Paul Clark', 'Return request', '2024-06-07');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (11, 'Maria Moore', 'Return request', '2023-09-12');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (12, 'Maria Moore', 'Login issue', '2024-03-30');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (13, 'Michael Lee', 'Return request', '2024-10-24');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (14, 'Sarah Johnson', 'Billing question', '2024-07-30');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (15, 'Patricia Harris', 'Damaged item', '2023-12-21');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (16, 'Jennifer Thompson', 'Invoice request', '2024-07-19');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (17, 'Michael Lee', 'Shipping delay', '2023-12-14');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (18, 'Sarah Johnson', 'Product question', '2024-02-20');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (19, 'Paul Wilson', 'Login issue', '2023-08-16');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (20, 'Jennifer Harris', 'Shipping delay', '2023-07-07');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (21, 'Jennifer Thompson', 'Damaged item', '2024-11-30');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (22, 'David Taylor', 'Invoice request', '2023-10-26');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (23, 'Susan Thomas', 'Billing question', '2023-06-14');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (24, 'James Davis', 'Damaged item', '2023-10-14');
INSERT INTO support_tickets (ticket_id, customer_name, issue_type, opened_date) VALUES (25, 'Paul Wilson', 'Product question', '2023-11-16');

